import React from 'react';
import { Container, Box, Typography, Card, Grid, Button, Chip } from '@mui/material';
import { Download, PictureAsPdf, TrendingUp, Assessment } from '@mui/icons-material';

const Reports = () => {
  const reports = [
    { id: 1, title: 'Weekly Threat Report', date: 'Jan 15, 2026', type: 'PDF', size: '2.4 MB' },
    { id: 2, title: 'Monthly Cybercrime Analysis', date: 'Jan 1, 2026', type: 'PDF', size: '5.8 MB' },
    { id: 3, title: 'Agent Performance Metrics', date: 'Dec 2025', type: 'Excel', size: '1.2 MB' },
    { id: 4, title: 'Regional Threat Intelligence', date: 'Dec 2025', type: 'PDF', size: '3.6 MB' },
  ];

  return (
    <Box sx={{ pt: { xs: 8, md: 10 }, pb: 6, minHeight: '100vh' }}>
      <Container maxWidth="lg">
        <Typography variant="h4" sx={{ fontWeight: 700, mb: 4 }}>
          <span className="gradient-text">Reports & Analytics</span>
          <Typography variant="caption" sx={{ display: 'block', color: '#8892b0', mt: 1 }}>
            Generated by the Cybercrime Reporting Agent
          </Typography>
        </Typography>
        <Grid container spacing={4}>
          <Grid item xs={12} md={8}>
            <Card sx={{ p: 3 }}>
              <Typography variant="h6" sx={{ mb: 3 }}>Generated Reports</Typography>
              <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
                {reports.map((r) => (
                  <Box key={r.id} sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center',
                    p: 2, borderRadius: 2, bgcolor: 'rgba(255,255,255,0.02)', border: '1px solid rgba(255,255,255,0.05)' }}>
                    <Box>
                      <Typography variant="body1" sx={{ fontWeight: 600 }}>{r.title}</Typography>
                      <Box sx={{ display: 'flex', gap: 2, mt: 0.5 }}>
                        <Typography variant="caption" sx={{ color: '#8892b0' }}>{r.date}</Typography>
                        <Chip label={r.type} size="small" sx={{ height: 20, fontSize: '0.6rem' }} />
                        <Typography variant="caption" sx={{ color: '#8892b0' }}>{r.size}</Typography>
                      </Box>
                    </Box>
                    <Button variant="outlined" size="small" startIcon={<Download />}
                      sx={{ borderColor: 'rgba(255,255,255,0.2)' }}>Download</Button>
                  </Box>
                ))}
              </Box>
            </Card>
          </Grid>
          <Grid item xs={12} md={4}>
            <Card sx={{ p: 3 }}>
              <Typography variant="h6" sx={{ mb: 3 }}>Quick Actions</Typography>
              <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
                <Button variant="contained" fullWidth startIcon={<PictureAsPdf />}
                  sx={{ background: 'linear-gradient(135deg, #00d4ff, #7b2ffc)' }}>Generate Report</Button>
                <Button variant="outlined" fullWidth startIcon={<TrendingUp />}
                  sx={{ borderColor: 'rgba(255,255,255,0.2)' }}>Analytics Dashboard</Button>
                <Button variant="outlined" fullWidth startIcon={<Assessment />}
                  sx={{ borderColor: 'rgba(255,255,255,0.2)' }}>Export Data</Button>
              </Box>
            </Card>
          </Grid>
        </Grid>
      </Container>
    </Box>
  );
};

export default Reports;