import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

export const languages = [
  { code: 'en', label: 'English' },
  { code: 'hi', label: 'हिन्दी' },
];

const translations = {
  en: {
    nav: { swarm: 'Swarm', dashboard: 'Dashboard', agents: 'Agents', reports: 'Reports', sos: 'SOS', login: 'Login' },
    login: {
      title: 'Secure Login with Face Authentication',
      faceButton: 'Login with Face',
      captureButton: 'Capture & Authenticate',
      cancel: 'Cancel',
      verified: 'Face verified! You are logged in.',
      goDashboard: 'Go to Dashboard',
      or: 'OR',
      email: 'Email Address',
      password: 'Password',
      signIn: 'Sign In',
      noAccount: "Don't have an account? Sign Up",
      forgot: 'Forgot password?',
    },
    dashboard: {
      title: 'Agent Swarm Dashboard',
      subtitle: 'Real‑time performance of the 12‑agent collective',
      sync: 'Sync Agents',
      export: 'Export Logs',
      performance: 'Agent Performance Metrics',
      accuracy: 'Accuracy',
      latency: 'Latency',
      communication: 'Agent Communication & Resolutions',
      workload: 'Workload by Agent',
      mapTitle: 'Threats Mapped by Location Intelligence Agent',
      feedTitle: 'Agent Activity Feed',
    },
    agents: {
      title: 'The Agentic Swarm',
      subtitle: '12 autonomous AI agents, each with a specialized model and purpose – they communicate and collaborate to protect you.',
      confidence: 'Confidence',
    },
    reports: {
      title: 'Reports & Analytics',
      subtitle: 'Generated by the Cybercrime Reporting Agent',
      generated: 'Generated Reports',
      date: 'Date',
      actions: 'Quick Actions',
      generate: 'Generate Report',
      analytics: 'Analytics Dashboard',
      exportData: 'Export Data',
    },
    sos: {
      title: 'Emergency SOS',
      subtitle: 'Orchestrated by the Emergency Response Agent',
      description: 'One-tap emergency alert system with live location sharing',
      hold: 'HOLD TO ACTIVATE',
      cancelling: 'Cancelling...',
      contacts: 'Emergency Contacts',
      call: 'Call',
      action: 'Emergency Action: Your location will be shared with all contacts above.',
      tip: 'Pro Tip: Hold the SOS button for 3 seconds to activate. Release to cancel.',
      report: 'Report Cybercrime',
      share: 'Share Location',
    },
    voice: {
      title: 'Voice Assistant',
      language: 'Language',
      start: 'Start Listening',
      stop: 'Stop',
      youSaid: 'You said:',
    },
    chatbot: {
      title: 'AI Chatbot',
      placeholder: 'Ask me anything...',
      send: 'Send',
    },
  },
  hi: {
    nav: { swarm: 'स्वार्म', dashboard: 'डैशबोर्ड', agents: 'एजेंट्स', reports: 'रिपोर्ट्स', sos: 'एसओएस', login: 'लॉगिन' },
    login: {
      title: 'चेहरा प्रमाणीकरण के साथ सुरक्षित लॉगिन',
      faceButton: 'चेहरे से लॉगिन करें',
      captureButton: 'कैप्चर करें और प्रमाणित करें',
      cancel: 'रद्द करें',
      verified: 'चेहरा सत्यापित! आप लॉगिन हो गए हैं।',
      goDashboard: 'डैशबोर्ड पर जाएं',
      or: 'या',
      email: 'ईमेल पता',
      password: 'पासवर्ड',
      signIn: 'साइन इन',
      noAccount: 'खाता नहीं है? साइन अप करें',
      forgot: 'पासवर्ड भूल गए?',
    },
    dashboard: {
      title: 'एजेंट स्वार्म डैशबोर्ड',
      subtitle: '12-एजेंट कलेक्टिव का रियल-टाइम प्रदर्शन',
      sync: 'एजेंट सिंक करें',
      export: 'लॉग निर्यात करें',
      performance: 'एजेंट प्रदर्शन मेट्रिक्स',
      accuracy: 'सटीकता',
      latency: 'विलंबता',
      communication: 'एजेंट संचार और समाधान',
      workload: 'एजेंट द्वारा कार्यभार',
      mapTitle: 'लोकेशन इंटेलिजेंस एजेंट द्वारा मैप किए गए खतरे',
      feedTitle: 'एजेंट गतिविधि फीड',
    },
    agents: {
      title: 'एजेंटिक स्वार्म',
      subtitle: '12 स्वायत्त AI एजेंट, प्रत्येक एक विशेष मॉडल और उद्देश्य के साथ – वे आपकी सुरक्षा के लिए संचार और सहयोग करते हैं।',
      confidence: 'विश्वास',
    },
    reports: {
      title: 'रिपोर्ट और एनालिटिक्स',
      subtitle: 'साइबरक्राइम रिपोर्टिंग एजेंट द्वारा उत्पन्न',
      generated: 'उत्पन्न रिपोर्ट',
      date: 'तारीख',
      actions: 'त्वरित कार्रवाई',
      generate: 'रिपोर्ट बनाएं',
      analytics: 'एनालिटिक्स डैशबोर्ड',
      exportData: 'डेटा निर्यात करें',
    },
    sos: {
      title: 'आपातकालीन SOS',
      subtitle: 'आपातकालीन प्रतिक्रिया एजेंट द्वारा संचालित',
      description: 'लाइव लोकेशन शेयरिंग के साथ वन-टैप आपातकालीन अलर्ट सिस्टम',
      hold: 'सक्रिय करने के लिए होल्ड करें',
      cancelling: 'रद्द हो रहा है...',
      contacts: 'आपातकालीन संपर्क',
      call: 'कॉल करें',
      action: 'आपातकालीन कार्रवाई: आपका स्थान ऊपर के सभी संपर्कों के साथ साझा किया जाएगा।',
      tip: 'टिप: सक्रिय करने के लिए SOS बटन को 3 सेकंड तक दबाए रखें। रद्द करने के लिए छोड़ दें।',
      report: 'साइबरक्राइम रिपोर्ट करें',
      share: 'स्थान साझा करें',
    },
    voice: {
      title: 'वॉइस असिस्टेंट',
      language: 'भाषा',
      start: 'सुनना शुरू करें',
      stop: 'रोकें',
      youSaid: 'आपने कहा:',
    },
    chatbot: {
      title: 'AI चैटबॉट',
      placeholder: 'कुछ भी पूछें...',
      send: 'भेजें',
    },
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  const t = (path) => {
    const keys = path.split('.');
    let result = translations[language];
    for (const key of keys) {
      if (result && result[key] !== undefined) {
        result = result[key];
      } else {
        return path;
      }
    }
    return result || path;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, languages }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
